apiVersion: v1
kind: Service
metadata:
  name: db-connect-nodeport-service
  namespace: default
spec:
  ports:
  - port: 32001
    nodePort: 32001
    targetPort: nginx-port
    protocol: TCP
  selector:
    app: db-connect
  type: NodePort