apiVersion: v1
kind: Service
metadata:
  name: db-connect-service
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: nginx-port
    protocol: TCP
  selector:
    app: db-connect
  type: LoadBalancer