apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: apache-port
    protocol: TCP
  selector:
    app: helloworld
  type: LoadBalancer